export interface District {
  name: string;
  areas: string[];
}

export interface Division {
  name: string;
  districts: Record<string, string[]>;
}

export const BANGLADESH_LOCATIONS: Record<string, Record<string, string[]>> = {
  Dhaka: {
    Dhaka: [
      "Dhanmondi",
      "Gulshan",
      "Banani",
      "Mirpur",
      "Uttara",
      "Mohammadpur",
      "Badda",
      "Motijheel",
      "Shahbagh",
      "Bashundhara R/A",
      "Rampura",
      "Khilgaon",
      "Tejgaon",
      "Old Dhaka",
      "Jatrabari",
      "Savar",
      "Keraniganj",
      "Dhamrai",
    ],
    Gazipur: [
      "Gazipur Sadar",
      "Tongi",
      "Kaliakair",
      "Kapasia",
      "Sreepur",
      "Kaliganj",
    ],
    Narayanganj: [
      "Narayanganj Sadar",
      "Bandar",
      "Fatullah",
      "Siddhirganj",
      "Araihazar",
      "Sonargaon",
      "Rupganj",
    ],
    Tangail: [
      "Tangail Sadar",
      "Mirzapur",
      "Madhupur",
      "Ghatail",
      "Gopalpur",
      "Sakhipur",
      "Kalihati",
      "Delduar",
    ],
    Narsingdi: [
      "Narsingdi Sadar",
      "Palash",
      "Shibpur",
      "Raipura",
      "Monohardi",
      "Belabo",
    ],
    Faridpur: [
      "Faridpur Sadar",
      "Boalmari",
      "Bhanga",
      "Madhukhali",
      "Nagarkanda",
      "Charbhadrasan",
    ],
    Manikganj: [
      "Manikganj Sadar",
      "Singair",
      "Saturia",
      "Shivalaya",
      "Harirampur",
      "Ghior",
      "Daulatpur",
    ],
    Munshiganj: [
      "Munshiganj Sadar",
      "Sreenagar",
      "Sirajdikhan",
      "Lohajang",
      "Tongibari",
      "Gazaria",
    ],
    Gopalganj: [
      "Gopalganj Sadar",
      "Kashiani",
      "Kotalipara",
      "Muksudpur",
      "Tungipara",
    ],
    Madaripur: ["Madaripur Sadar", "Shibchar", "Kalkini", "Rajoir"],
    Rajbari: [
      "Rajbari Sadar",
      "Goalanda",
      "Pangsha",
      "Baliakandi",
      "Kalukhali",
    ],
    Shariatpur: [
      "Shariatpur Sadar",
      "Damudya",
      "Naria",
      "Janjira",
      "Bhedarganj",
      "Gosairhat",
    ],
    Kishoreganj: [
      "Kishoreganj Sadar",
      "Bhairab",
      "Bajitpur",
      "Katiadi",
      "Pakundia",
      "Karimganj",
      "Tarail",
      "Hossainpur",
      "Kuliarchar",
      "Nikli",
      "Itna",
      "Mithamoin",
      "Austagram",
    ],
  },
  Chattogram: {
    Chattogram: [
      "Agrabad",
      "GEC",
      "Nasirabad",
      "Panchlaish",
      "Halishahar",
      "Khulshi",
      "Kotwali",
      "Pahartali",
      "Bakalia",
      "Chawkbazar",
      "Patenga",
      "Hathazari",
      "Sitakunda",
      "Mirsharai",
      "Patiya",
      "Raozan",
      "Fatikchhari",
      "Boalkhali",
      "Anwara",
      "Chandanaish",
      "Lohagara",
      "Satkania",
      "Banshkhali",
    ],
    "Cox's Bazar": [
      "Cox's Bazar Sadar",
      "Ramu",
      "Chakaria",
      "Teknaf",
      "Ukhia",
      "Pekua",
      "Kutubdia",
      "Maheshkhali",
    ],
    Cumilla: [
      "Cumilla Sadar",
      "Laksam",
      "Daudkandi",
      "Debidwar",
      "Chandina",
      "Burichang",
      "Brahmanpara",
      "Chauddagram",
      "Homna",
      "Muradnagar",
      "Barura",
      "Meghna",
      "Titas",
      "Monohargonj",
      "Lalmai",
    ],
    Feni: [
      "Feni Sadar",
      "Chhagalnaiya",
      "Daganbhuiyan",
      "Parshuram",
      "Fulgazi",
      "Sonagazi",
    ],
    Brahmanbaria: [
      "Brahmanbaria Sadar",
      "Ashuganj",
      "Sarail",
      "Kasba",
      "Nabinagar",
      "Bancharampur",
      "Akhaura",
      "Nasirnagar",
      "Bijoynagar",
    ],
    Noakhali: [
      "Noakhali Sadar",
      "Begumganj",
      "Chatkhil",
      "Companiganj",
      "Hatiya",
      "Senbagh",
      "Subarnachar",
      "Kabirhat",
      "Sonaimuri",
    ],
    Chandpur: [
      "Chandpur Sadar",
      "Hajiganj",
      "Matlab North",
      "Matlab South",
      "Faridganj",
      "Shahrasti",
      "Kachua",
      "Haimchar",
    ],
    Lakshmipur: [
      "Lakshmipur Sadar",
      "Raipur",
      "Ramganj",
      "Ramgati",
      "Kamalnagar",
    ],
    Rangamati: [
      "Rangamati Sadar",
      "Kaptai",
      "Baghaichhari",
      "Barkal",
      "Langadu",
      "Rajasthali",
      "Belaichhari",
      "Juraichhari",
      "Naniarchar",
      "Kaukhali",
    ],
    Khagrachhari: [
      "Khagrachhari Sadar",
      "Dighinala",
      "Panchhari",
      "Mahalchhari",
      "Matiranga",
      "Manikchhari",
      "Ramgarh",
      "Guimara",
      "Lakshmichhari",
    ],
    Bandarban: [
      "Bandarban Sadar",
      "Ruma",
      "Thanchi",
      "Lama",
      "Alikadam",
      "Naikhongchhari",
      "Rowangchhari",
    ],
  },
  Rajshahi: {
    Rajshahi: [
      "Boalia",
      "Motihar",
      "Rajpara",
      "Shah Makhdum",
      "Godagari",
      "Tanore",
      "Paba",
      "Bagmara",
      "Durgapur",
      "Puthia",
      "Charghat",
      "Bagha",
    ],
    Bogura: [
      "Bogura Sadar",
      "Shajahanpur",
      "Sherpur",
      "Shibganj",
      "Dhunat",
      "Gabtali",
      "Kahaloo",
      "Nandigram",
      "Sariakandi",
      "Sonatala",
      "Adamdighi",
      "Dupchanchia",
    ],
    Pabna: [
      "Pabna Sadar",
      "Ishwardi",
      "Santhia",
      "Bera",
      "Chatmohar",
      "Faridpur",
      "Atgharia",
      "Sujanagar",
      "Bhangura",
    ],
    Sirajganj: [
      "Sirajganj Sadar",
      "Belkuchi",
      "Chauhali",
      "Kamarkhanda",
      "Kazipur",
      "Raiganj",
      "Shahjadpur",
      "Tarash",
      "Ullapara",
    ],
    Naogaon: [
      "Naogaon Sadar",
      "Mohadevpur",
      "Patnitala",
      "Dhamoirhat",
      "Sapahar",
      "Porsha",
      "Manda",
      "Niamatpur",
      "Atrai",
      "Raninagar",
      "Badalgachhi",
    ],
    Natore: [
      "Natore Sadar",
      "Baraigram",
      "Bagatipara",
      "Gurudaspur",
      "Lalpur",
      "Singra",
      "Naldanga",
    ],
    ChapaiNawabganj: [
      "Chapai Nawabganj Sadar",
      "Shibganj",
      "Gomostapur",
      "Nachole",
      "Bholahat",
    ],
    Joypurhat: ["Joypurhat Sadar", "Panchbibi", "Kalai", "Khetlal", "Akkelpur"],
  },
  Khulna: {
    Khulna: [
      "Khulna Sadar",
      "Sonadanga",
      "Khalishpur",
      "Daulatpur",
      "Khan Jahan Ali",
      "Dumuria",
      "Batiaghata",
      "Dacope",
      "Paikgachha",
      "Koyra",
      "Rupsha",
      "Terokhada",
      "Dighalia",
    ],
    Jashore: [
      "Jashore Sadar",
      "Jhikargachha",
      "Sharsha",
      "Abhaynagar",
      "Bagherpara",
      "Chaugachha",
      "Keshabpur",
      "Manirampur",
    ],
    Kushtia: [
      "Kushtia Sadar",
      "Kumarkhali",
      "Khoksa",
      "Mirpur",
      "Bheramara",
      "Daulatpur",
    ],
    Satkhira: [
      "Satkhira Sadar",
      "Assasuni",
      "Debhata",
      "Kalaroa",
      "Kaliganj",
      "Shyamnagar",
      "Tala",
    ],
    Bagerhat: [
      "Bagerhat Sadar",
      "Mongla",
      "Morrelganj",
      "Fakirhat",
      "Kachua",
      "Mollahat",
      "Rampal",
      "Rupsha",
      "Sarankhola",
      "Chitalmari",
    ],
    Jhenaidah: [
      "Jhenaidah Sadar",
      "Harakunda",
      "Kaliganj",
      "Kotchandpur",
      "Maheshpur",
      "Shailkupa",
    ],
    Chuadanga: ["Chuadanga Sadar", "Alamdanga", "Damurhuda", "Jibannagar"],
    Magura: ["Magura Sadar", "Mohammadpur", "Shalikha", "Sreepur"],
    Meherpur: ["Meherpur Sadar", "Gangni", "Mujibnagar"],
    Narail: ["Narail Sadar", "Kalia", "Lohagara"],
  },
  Barishal: {
    Barishal: [
      "Barishal Sadar",
      "Bakerganj",
      "Babuganj",
      "Banaripara",
      "Gournadi",
      "Hizla",
      "Mehendiganj",
      "Muladi",
      "Wazirpur",
      "Agailjhara",
    ],
    Bhola: [
      "Bhola Sadar",
      "Burhanuddin",
      "Char Fasson",
      "Daulatkhan",
      "Lalmohan",
      "Manpura",
      "Tazumuddin",
    ],
    Patuakhali: [
      "Patuakhali Sadar",
      "Bauphal",
      "Dashmina",
      "Galachipa",
      "Kalapara",
      "Mirzaganj",
      "Rangabali",
      "Dumki",
    ],
    Pirojpur: [
      "Pirojpur Sadar",
      "Bhandaria",
      "Kawkhali",
      "Mathbaria",
      "Nazirpur",
      "Nesarabad (Swarupkati)",
      "Zianagar (Indurkani)",
    ],
    Barguna: [
      "Barguna Sadar",
      "Amtali",
      "Betagi",
      "Bamna",
      "Patharghata",
      "Taltali",
    ],
    Jhalokathi: ["Jhalokathi Sadar", "Kathalia", "Nalchity", "Rajapur"],
  },
  Sylhet: {
    Sylhet: [
      "Sylhet Sadar",
      "Beanibazar",
      "Golapganj",
      "Companiganj",
      "Fenchuganj",
      "Balaganj",
      "Biswanath",
      "Gowainghat",
      "Jaintiapur",
      "Kanaighat",
      "Zakiganj",
      "Dakshin Surma",
      "Osmani Nagar",
    ],
    Moulvibazar: [
      "Moulvibazar Sadar",
      "Sreemangal",
      "Kamalganj",
      "Kulaura",
      "Rajnagar",
      "Barlekha",
      "Juri",
    ],
    Habiganj: [
      "Habiganj Sadar",
      "Bahubal",
      "Chunarughat",
      "Madhabpur",
      "Nabiganj",
      "Baniachong",
      "Ajmiriganj",
      "Lakhai",
      "Shayestaganj",
    ],
    Sunamganj: [
      "Sunamganj Sadar",
      "Chhatak",
      "Jagannathpur",
      "Derai",
      "Dharampasha",
      "Dowarabazar",
      "Jamalgang",
      "Shantiganj",
      "Sullah",
      "Tahirpur",
      "Biswamvarpur",
      "Madhyanagar",
    ],
  },
  Rangpur: {
    Rangpur: [
      "Rangpur Sadar",
      "Badarganj",
      "Gangachhara",
      "Kaunia",
      "Mithapukur",
      "Pirgachha",
      "Pirganj",
      "Taraganj",
    ],
    Dinajpur: [
      "Dinajpur Sadar",
      "Birganj",
      "Biral",
      "Bochaganj",
      "Chirirbandar",
      "Fulbari",
      "Ghoraghat",
      "Hakimpur",
      "Kaharole",
      "Khansama",
      "Nawabganj",
      "Parbatipur",
    ],
    Gaibandha: [
      "Gaibandha Sadar",
      "Gobindaganj",
      "Palashbari",
      "Sadullapur",
      "Saghata",
      "Sundarganj",
      "Fulchhari",
    ],
    Kurigram: [
      "Kurigram Sadar",
      "Nageshwari",
      "Bhurungamari",
      "Phulbari",
      "Rajarhat",
      "Ulipur",
      "Chilmari",
      "Rowmari",
      "Char Rajibpur",
    ],
    Nilphamari: [
      "Nilphamari Sadar",
      "Saidpur",
      "Domar",
      "Dimla",
      "Jaldhaka",
      "Kishoreganj",
    ],
    Lalmonirhat: [
      "Lalmonirhat Sadar",
      "Aditmari",
      "Kaliganj",
      "Hatibandha",
      "Patgram",
    ],
    Thakurgaon: [
      "Thakurgaon Sadar",
      "Pirganj",
      "Ranisankail",
      "Baliadangi",
      "Haripur",
    ],
    Panchagarh: ["Panchagarh Sadar", "Boda", "Debiganj", "Atwari", "Tetulia"],
  },
  Mymensingh: {
    Mymensingh: [
      "Mymensingh Sadar",
      "Trishal",
      "Bhaluka",
      "Muktagachha",
      "Gafargaon",
      "Fulbaria",
      "Ishwarganj",
      "Nandail",
      "Gouripur",
      "Haluaghat",
      "Dhobaura",
      "Tara Khanda",
    ],
    Jamalpur: [
      "Jamalpur Sadar",
      "Baksiganj",
      "Dewanganj",
      "Islampur",
      "Madarganj",
      "Melandaha",
      "Sarishabari",
    ],
    Netrokona: [
      "Netrokona Sadar",
      "Barhatta",
      "Durgapur",
      "Kendua",
      "Kalmakanda",
      "Madan",
      "Mohanganj",
      "Purbadhala",
      "Khaliajuri",
      "Atpara",
    ],
    Sherpur: [
      "Sherpur Sadar",
      "Nalitabari",
      "Nakla",
      "Sreebardi",
      "Jhenaigati",
    ],
  },
};

export const DIVISIONS = Object.keys(BANGLADESH_LOCATIONS);
